projects = [
    {
        'name': 'Pot Hole',
        'description': 'Pot hole near Indiranagar 100ft roadi',
        'website': 'http://goibibo.com',
        'thumbnail': 'images/Anne-Teubert600_758.jpg',
        'total_funds':  2000.00,
        'self_funds': 100.00,
        'donations': 1500.00,
        'expenditure': 300.00,
        'progress': 30.00,
        'organisation_id': '',
        'organisation_name': '',
        'status': 'work_in_progress',
        'creator_user_id': '',
        'creator_username': '',
        'owner_user_id': '1',
        'owner_username': 'vireshas',
        'created': '09-05-2014',
        'last_updated': ''
    },
    {
        'name': 'Pot Hole',
        'description': 'Pot hole near Indiranagar 100ft roadi',
        'website': 'http://goibibo.com',
        'thumbnail': 'images/Anne-Teubert600_758.jpg',
        'total_funds':  2000.00,
        'self_funds': 100.00,
        'donations': 1500.00,
        'expenditure': 300.00,
        'progress': 30.00,
        'organisation_id': '',
        'organisation_name': '',
        'status': 'work_in_progress',
        'creator_user_id': '',
        'creator_username': '',
        'owner_user_id': '1',
        'owner_username': 'vireshas',
        'created': '09-05-2014',
        'last_updated': ''
    },
    {
        'name': 'Pot Hole',
        'description': 'Pot hole near Indiranagar 100ft roadi',
        'website': 'http://goibibo.com',
        'thumbnail': 'images/Anne-Teubert600_758.jpg',
        'total_funds':  2000.00,
        'self_funds': 100.00,
        'donations': 1500.00,
        'expenditure': 300.00,
        'progress': 30.00,
        'organisation_id': '',
        'organisation_name': '',
        'status': 'work_in_progress',
        'creator_user_id': '',
        'creator_username': '',
        'owner_user_id': '1',
        'owner_username': 'vireshas',
        'created': '09-05-2014',
        'last_updated': ''
    },
    {
        'name': 'Pot Hole',
        'description': 'Pot hole near Indiranagar 100ft roadi',
        'website': 'http://goibibo.com',
        'thumbnail': 'images/Anne-Teubert600_758.jpg',
        'total_funds':  2000.00,
        'self_funds': 100.00,
        'donations': 1500.00,
        'expenditure': 300.00,
        'progress': 30.00,
        'organisation_id': '',
        'organisation_name': '',
        'status': 'work_in_progress',
        'creator_user_id': '',
        'creator_username': '',
        'owner_user_id': '1',
        'owner_username': 'vireshas',
        'created': '09-05-2014',
        'last_updated': ''
    },
    {
        'name': 'Pot Hole',
        'description': 'Pot hole near Indiranagar 100ft roadi',
        'website': 'http://goibibo.com',
        'thumbnail': 'images/Anne-Teubert600_758.jpg',
        'total_funds':  2000.00,
        'self_funds': 100.00,
        'donations': 1500.00,
        'expenditure': 300.00,
        'progress': 30.00,
        'organisation_id': '',
        'organisation_name': '',
        'status': 'work_in_progress',
        'creator_user_id': '',
        'creator_username': '',
        'owner_user_id': '1',
        'owner_username': 'vireshas',
        'created': '09-05-2014',
        'last_updated': ''
    },
    {
        'name': 'Pot Hole',
        'description': 'Pot hole near Indiranagar 100ft roadi',
        'website': 'http://goibibo.com',
        'thumbnail': 'images/Anne-Teubert600_758.jpg',
        'total_funds':  2000.00,
        'self_funds': 100.00,
        'donations': 1500.00,
        'expenditure': 300.00,
        'progress': 30.00,
        'organisation_id': '',
        'organisation_name': '',
        'status': 'work_in_progress',
        'creator_user_id': '',
        'creator_username': '',
        'owner_user_id': '1',
        'owner_username': 'vireshas',
        'created': '09-05-2014',
        'last_updated': ''
    }
]
