milestones = [
    {
        'name': '10ft section',
        'description': 'Deepest pot hole',
        'project_id': '1',
        'project_name': 'Pot Hole',
        'total_funds' : 50.00,
        'expenditure': 25.00,
        'progress' : 30.00,
        'status': 'work_in_progress',
        'created': '09-05-2014',
        'last_updated': '09-05-2014',
        'creator_user_id': '1',
        'creator_user_name': 'vireshas'
    },
    {
        'name': '10ft section',
        'description': 'Deepest pot hole',
        'project_id': '1',
        'project_name': 'Pot Hole',
        'total_funds' : 50.00,
        'expenditure': 25.00,
        'progress' : 30.00,
        'status': 'work_in_progress',
        'created': '09-05-2014',
        'last_updated': '09-05-2014',
        'creator_user_id': '1',
        'creator_user_name': 'vireshas'
    },
    {
        'name': '10ft section',
        'description': 'Deepest pot hole',
        'project_id': '1',
        'project_name': 'Pot Hole',
        'total_funds' : 50.00,
        'expenditure': 25.00,
        'progress' : 30.00,
        'status': 'work_in_progress',
        'created': '09-05-2014',
        'last_updated': '09-05-2014',
        'creator_user_id': '1',
        'creator_user_name': 'vireshas'
    },
    {
        'name': '10ft section',
        'description': 'Deepest pot hole',
        'project_id': '1',
        'project_name': 'Pot Hole',
        'total_funds' : 50.00,
        'expenditure': 25.00,
        'progress' : 30.00,
        'status': 'work_in_progress',
        'created': '09-05-2014',
        'last_updated': '09-05-2014',
        'creator_user_id': '1',
        'creator_user_name': 'vireshas'
    },
    {
        'name': '10ft section',
        'description': 'Deepest pot hole',
        'project_id': '1',
        'project_name': 'Pot Hole',
        'total_funds' : 50.00,
        'expenditure': 25.00,
        'progress' : 30.00,
        'status': 'work_in_progress',
        'created': '09-05-2014',
        'last_updated': '09-05-2014',
        'creator_user_id': '1',
        'creator_user_name': 'vireshas'
    },
    {
        'name': '10ft section',
        'description': 'Deepest pot hole',
        'project_id': '1',
        'project_name': 'Pot Hole',
        'total_funds' : 50.00,
        'expenditure': 25.00,
        'progress' : 30.00,
        'status': 'work_in_progress',
        'created': '09-05-2014',
        'last_updated': '09-05-2014',
        'creator_user_id': '1',
        'creator_user_name': 'vireshas'
    },
    {
        'name': '10ft section',
        'description': 'Deepest pot hole',
        'project_id': '1',
        'project_name': 'Pot Hole',
        'total_funds' : 50.00,
        'expenditure': 25.00,
        'progress' : 30.00,
        'status': 'work_in_progress',
        'created': '09-05-2014',
        'last_updated': '09-05-2014',
        'creator_user_id': '1',
        'creator_user_name': 'vireshas'
    }
]
